### ISSUE TITLE
在linux 中运行出错了

### ISSUE THREAD

**Issue by jpstring2019** [Lockey-J/DdddOcrSharp#1]
An unhandled exception was thrown by the application.
      System.TypeInitializationException: The type initializer for 'OpenCvSharp.Internal.NativeMethods' threw an exception.
       ---> System.DllNotFoundException: Unable to load shared library 'OpenCvSharpExtern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libOpenCvSharpExtern: cannot open shared object file: No such file or directory
         at OpenCvSharp.Internal.NativeMethods.redirectError(CvErrorCallback errCallback, IntPtr userdata, IntPtr& prevUserdata)
         at OpenCvSharp.Internal.ExceptionHandler.RegisterExceptionCallback()
         at OpenCvSharp.Internal.NativeMethods.LoadLibraries(IEnumerable`1 additionalPaths)
         at OpenCvSharp.Internal.NativeMethods..cctor()
         --- End of inner exception stack trace ---
         at OpenCvSharp.Internal.NativeMethods.imgcodecs_imread(String fileName, Int32 flags, IntPtr& returnValue)
         at OpenCvSharp.Mat..ctor(String fileName, ImreadModes flags)
         at Lt.Service.VerifyCode.DdddOcr_Hepper.ClassifyBeta(VerifyCodeParms parms) in D:\GitCode\LotteryV2\Lottery.Service\Lt.Servic

**Comment by Lockey-J** [comment]
OpenCvSharp你的lib需要用对应的linux版本。
